#!/bin/bash
set -e
cd "$(dirname "$0")"

PACKS="pack/jasonk/start"

mkdir -p "$PACKS"

get_repos() {
  sed -n 's,^" *Plugin,,p' "$1" | sed -e "s/^ *'//" -e "s/ *' *//"
}
get_all_repos() {
  local FILE
  for FILE in plugins/*.vim; do
    get_repos "$FILE"
  done
}

for REPO in $(get_all_repos); do
  NAME="$(basename "$REPO" .vim)"
  echo "$NAME - $REPO"
  if [ ! -d "$PACKS/$NAME" ]; then
    # git submodule add "https://github.com/$REPO" "$PACKS/$NAME"
    git clone "https://github.com/$REPO" "$PACKS/$NAME"
  fi
done

(
  echo '" Do not edit this file!  It is generated by setup.sh'
  grep -lv '^"' plugins/*.vim | while read -r FILE; do
    echo "source ~/.vim/$FILE"
  done
) > ./plugins.vim

cd "$HOME"
for V in "$HOME/.vimrc" "$HOME/.gvimrc"; do
  ln -sf "$HOME/.vim/vimrc" "$V"
done
