#!/bin/bash

# See https://github.com/VSCodeVim/Vim
if is_mac; then
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
fi
# For VS Code Insider
# defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
# If necessary, reset global default
# defaults delete -g ApplePressAndHoldEnabled
