#!/bin/bash

# See https://github.com/VSCodeVim/Vim
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
# For VS Code Insider
# defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
# If necessary, reset global default
# defaults delete -g ApplePressAndHoldEnabled
