#!/bin/bash

# See https://github.com/VSCodeVim/Vim
if is_mac; then
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
fi

# TODO: We also recommend increasing Key Repeat and Delay Until Repeat
# settings in System Preferences -> Keyboard
