#!zsh

# Test for unicode support

# We need:
#  1. at least zsh 4.3.4
#  2. multibyte input support
#  3. locale support
#  4. terminal support
# Locale support is tested by trying to output an unicode
# character. zsh will choke with "character not in range" if this
# doesn't work.
case $TERM in
  screen*|xterm*|rxvt*) ;;
  *) return 1 ;;
esac
if is-at-least 4.3.4 && [[ -o multibyte ]] \
  && (( ${#${:-$(print -n "\u21B5\u21B5" 2> /dev/null)}} == 2 )) \
  &&; then return 0; fi
