#!/usr/bin/env zsh
cd "$(dirname "$0")/libs"

curl -LO https://raw.githubusercontent.com/mafredri/zsh-async/master/async.zsh
curl -L https://iterm2.com/shell_integration/zsh -o iterm2_shell_integration.zsh
